import "flag-icons/css/flag-icons.css";
import '@/app/styles/globals.scss'

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({children}: { children: React.ReactNode }): JSX.Element {
    return (
        <html>
        <body>
        {children}
        </body>
        </html>
    )
}
