import "flag-icons/css/flag-icons.css";
import '@/app/styles/globals.scss'
import { dir } from 'i18next'

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({children, params}: {children: React.ReactNode, params: {lng: string}}): JSX.Element {
    const { lng } = params

    return (
        <html lang={lng} dir={dir(lng)}>
        <body>
        {children}
        </body>
        </html>
    )
}
