import "flag-icons/css/flag-icons.css";
import '@/app/styles/globals.scss'
import { dir } from 'i18next'
import {allLanguages} from "@/app/i18n/server-i18n-conf";
import LanguageDef from "@/app/i18n/language-def";

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export async function generateStaticParams(): Promise<{params: {lng: string} }[]> {
    return (await allLanguages()).map((l: LanguageDef) => {return {params: {lng: l.key}};});
}

export default function RootLayout({children, params}: {children: React.ReactNode, params: {lng: string}}): JSX.Element {
    const { lng } = params

    return (
        <html lang={lng} dir={dir(lng)}>
        <body>
        {children}
        </body>
        </html>
    )
}
